//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GymBuddy.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblNutritionPlan
    {
        public int nutritionID { get; set; }
        public string nutritionName { get; set; }
        public Nullable<System.DateTime> nutritionStart { get; set; }
        public Nullable<System.DateTime> nutritionEnd { get; set; }
        public Nullable<decimal> carb { get; set; }
        public Nullable<decimal> fat { get; set; }
        public Nullable<decimal> saturatedFat { get; set; }
        public Nullable<decimal> protien { get; set; }
        public Nullable<decimal> sugar { get; set; }
        public string nutritionDescription { get; set; }
        public Nullable<int> userID { get; set; }
    
        public virtual tblUser tblUser { get; set; }
    }
}
