//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GymBuddy.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblUser
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblUser()
        {
            this.tblNutritionPlans = new HashSet<tblNutritionPlan>();
            this.tblWorkOutPlans = new HashSet<tblWorkOutPlan>();
        }
    
        public int userID { get; set; }
        public string firstName { get; set; }
        public string lastName { get; set; }
        public string userName { get; set; }
        public string phoneNO { get; set; }
        public string email { get; set; }
        public string password { get; set; }
        public string userType { get; set; }
        public string addressLine1 { get; set; }
        public string addressLine2 { get; set; }
        public string country { get; set; }
        public string city { get; set; }
        public string postCode { get; set; }
        public Nullable<int> coachID { get; set; }
        public Nullable<int> requestStatus { get; set; }
        public Nullable<int> nutritionStatus { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblNutritionPlan> tblNutritionPlans { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblWorkOutPlan> tblWorkOutPlans { get; set; }
    }
}
