//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GymBuddy.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblWorkOutPlan
    {
        public int workOutID { get; set; }
        public string workOutType { get; set; }
        public string targetArea { get; set; }
        public Nullable<System.DateTime> workOutStart { get; set; }
        public Nullable<System.DateTime> workOutEnd { get; set; }
        public Nullable<int> workOutDuration { get; set; }
        public string workOutDescription { get; set; }
        public Nullable<int> userID { get; set; }
    
        public virtual tblUser tblUser { get; set; }
    }
}
